apiVersion: v1
kind: Service
metadata:
  name: spark-master
spec:
  selector:
    app: spark
    role: master
  ports:
    - name: spark-master
      port: 7077
      targetPort: 7077
    - name: spark-ui
      port: 8080
      targetPort: 8080

