apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark
      role: master
  template:
    metadata:
      labels:
        app: spark
        role: master
    spec:
      containers:
        - name: spark-master
          image: spark-py:local
          env:
            - name: SPARK_MODE
              value: master
          ports:
            - containerPort: 7077
            - containerPort: 8080
          volumeMounts:
            - name: work-dir
              mountPath: /opt/spark/work-dir
      volumes:
        - name: work-dir
          emptyDir:
            sizeLimit: 500Mi

